[package]
name = "tkrpbot"
version = "0.1.0"
authors = ["Pedro Costa Neves <costa.neves@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
